[19-Jul-2018 00:00:05 Pacific/Pago_Pago] Uncaught Exception: 'ErrorException'With message: 'Division by zero'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(496): Core\Error::errorHandler(2, 'Division by zer...', '/home1/private/...', 496, Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(940): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processbAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processb', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processb')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line496
[19-Jul-2018 00:16:07 Pacific/Pago_Pago] Uncaught Exception: 'InstagramAPI\Exception\ChallengeRequiredException'With message: 'InstagramAPI\Response\LoginResponse: Challenge required.'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Client.php(555): InstagramAPI\Exception\ServerMessageThrower::autoThrow('InstagramAPI\\Re...', 'challenge_requi...', Object(InstagramAPI\Response\LoginResponse), Object(GuzzleHttp\Psr7\Response))
#1 /home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Request.php(793): InstagramAPI\Client->mapServerResponse(Object(InstagramAPI\Response\LoginResponse), '{"message": "ch...', Object(GuzzleHttp\Psr7\Response))
#2 /home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php(496): InstagramAPI\Request->getResponse(Object(InstagramAPI\Response\LoginResponse))
#3 /home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php(444): InstagramAPI\Instagram->_login('meowsme', 'k3kC1yxA', false, 1800)
#4 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(607): InstagramAPI\Instagram->login('meowsme', 'k3kC1yxA')
#5 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(940): App\Controllers\Task->processfunction()
#6 [internal function]: App\Controllers\Task->processbAction()
#7 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#8 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processb', Array)
#9 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processb')
#10 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Exception/ServerMessageThrower.php' on line189
[19-Jul-2018 00:19:10 Pacific/Pago_Pago] Uncaught Exception: 'ErrorException'With message: 'Division by zero'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(709): Core\Error::errorHandler(2, 'Division by zer...', '/home1/private/...', 709, Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(952): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processdAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processd', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processd')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line709
[19-Jul-2018 00:23:14 Pacific/Pago_Pago] Uncaught Exception: 'ErrorException'With message: 'Division by zero'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(496): Core\Error::errorHandler(2, 'Division by zer...', '/home1/private/...', 496, Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(957): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processeAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processe', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processe')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line496
[19-Jul-2018 00:23:24 Pacific/Pago_Pago] Uncaught Exception: 'LazyJsonMapper\Exception\LazyJsonMapperException'With message: 'Unknown function "getCode".'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(1317): LazyJsonMapper\LazyJsonMapper->__call('getCode', Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(822): App\Controllers\Task->loop_through_medias(Object(InstagramAPI\Instagram), 'usernames', Object(App\Models\Tasks), Array, Array, 200, Array)
#2 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(962): App\Controllers\Task->processfunction()
#3 [internal function]: App\Controllers\Task->processfAction()
#4 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#5 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processf', Array)
#6 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processf')
#7 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/lazyjsonmapper/lazyjsonmapper/src/LazyJsonMapper.php' on line2156
[19-Jul-2018 00:32:04 Pacific/Pago_Pago] Uncaught Exception: 'InvalidArgumentException'With message: 'You must provide a username and password to login().'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(1145): InstagramAPI\Instagram->login(NULL, NULL)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(741): App\Controllers\Task->likeMedia(Object(App\Models\Tasks), '180804303243702...', false)
#2 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(940): App\Controllers\Task->processfunction()
#3 [internal function]: App\Controllers\Task->processbAction()
#4 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#5 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processb', Array)
#6 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processb')
#7 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php' on line441
[19-Jul-2018 00:38:11 Pacific/Pago_Pago] Uncaught Exception: 'InvalidArgumentException'With message: 'You must provide a username and password to login().'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(1145): InstagramAPI\Instagram->login(NULL, NULL)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(794): App\Controllers\Task->likeMedia(Object(App\Models\Tasks), '180800029350368...', false)
#2 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(952): App\Controllers\Task->processfunction()
#3 [internal function]: App\Controllers\Task->processdAction()
#4 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#5 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processd', Array)
#6 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processd')
#7 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php' on line441
[19-Jul-2018 00:40:01 Pacific/Pago_Pago] Uncaught Exception: 'InvalidArgumentException'With message: 'You must provide a username and password to login().'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(458): InstagramAPI\Instagram->login(NULL, NULL)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(934): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processaAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processa', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processa')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php' on line441
[19-Jul-2018 00:44:07 Pacific/Pago_Pago] Uncaught Exception: 'InvalidArgumentException'With message: 'You must provide a username and password to login().'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(458): InstagramAPI\Instagram->login(NULL, NULL)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(946): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processcAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processc', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processc')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php' on line441
[19-Jul-2018 00:46:19 Pacific/Pago_Pago] Uncaught Exception: 'LazyJsonMapper\Exception\LazyJsonMapperException'With message: 'Unknown function "getCode".'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(1317): LazyJsonMapper\LazyJsonMapper->__call('getCode', Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(822): App\Controllers\Task->loop_through_medias(Object(InstagramAPI\Instagram), 'usernames', Object(App\Models\Tasks), Array, Array, 500, Array)
#2 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(962): App\Controllers\Task->processfunction()
#3 [internal function]: App\Controllers\Task->processfAction()
#4 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#5 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processf', Array)
#6 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processf')
#7 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/lazyjsonmapper/lazyjsonmapper/src/LazyJsonMapper.php' on line2156
[19-Jul-2018 00:46:21 Pacific/Pago_Pago] Uncaught Exception: 'LazyJsonMapper\Exception\LazyJsonMapperException'With message: 'Unknown function "getCode".'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(1317): LazyJsonMapper\LazyJsonMapper->__call('getCode', Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(822): App\Controllers\Task->loop_through_medias(Object(InstagramAPI\Instagram), 'usernames', Object(App\Models\Tasks), Array, Array, 550, Array)
#2 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(957): App\Controllers\Task->processfunction()
#3 [internal function]: App\Controllers\Task->processeAction()
#4 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#5 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processe', Array)
#6 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processe')
#7 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/lazyjsonmapper/lazyjsonmapper/src/LazyJsonMapper.php' on line2156
[19-Jul-2018 01:00:09 Pacific/Pago_Pago] Uncaught Exception: 'ErrorException'With message: 'Division by zero'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(814): Core\Error::errorHandler(2, 'Division by zer...', '/home1/private/...', 814, Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(946): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processcAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processc', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processc')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line814
[19-Jul-2018 01:00:21 Pacific/Pago_Pago] Uncaught Exception: 'Error'With message: 'Call to undefined method App\Models\Tasks::getRrecordById()'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(668): App\Controllers\Task->add_new_record(Object(App\Models\Tasks), '7216197231', 'chef_meijer')
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(962): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processfAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processf', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processf')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line974
[19-Jul-2018 01:00:22 Pacific/Pago_Pago] Uncaught Exception: 'Error'With message: 'Call to undefined method App\Models\Tasks::getRrecordById()'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(668): App\Controllers\Task->add_new_record(Object(App\Models\Tasks), '7216197231', 'chef_meijer')
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(957): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processeAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processe', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processe')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line974
[19-Jul-2018 01:19:10 Pacific/Pago_Pago] Uncaught Exception: 'ErrorException'With message: 'Division by zero'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(496): Core\Error::errorHandler(2, 'Division by zer...', '/home1/private/...', 496, Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(952): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processdAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processd', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processd')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line496
[19-Jul-2018 01:32:07 Pacific/Pago_Pago] Uncaught Exception: 'InstagramAPI\Exception\ChallengeRequiredException'With message: 'InstagramAPI\Response\LoginResponse: Challenge required.'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Client.php(555): InstagramAPI\Exception\ServerMessageThrower::autoThrow('InstagramAPI\\Re...', 'challenge_requi...', Object(InstagramAPI\Response\LoginResponse), Object(GuzzleHttp\Psr7\Response))
#1 /home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Request.php(793): InstagramAPI\Client->mapServerResponse(Object(InstagramAPI\Response\LoginResponse), '{"message": "ch...', Object(GuzzleHttp\Psr7\Response))
#2 /home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php(496): InstagramAPI\Request->getResponse(Object(InstagramAPI\Response\LoginResponse))
#3 /home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php(444): InstagramAPI\Instagram->_login('meowsme', 'k3kC1yxA', false, 1800)
#4 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(607): InstagramAPI\Instagram->login('meowsme', 'k3kC1yxA')
#5 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(940): App\Controllers\Task->processfunction()
#6 [internal function]: App\Controllers\Task->processbAction()
#7 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#8 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processb', Array)
#9 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processb')
#10 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Exception/ServerMessageThrower.php' on line189
[19-Jul-2018 01:38:11 Pacific/Pago_Pago] Uncaught Exception: 'ErrorException'With message: 'Division by zero'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(709): Core\Error::errorHandler(2, 'Division by zer...', '/home1/private/...', 709, Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(952): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processdAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processd', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processd')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line709
[19-Jul-2018 01:46:13 Pacific/Pago_Pago] Uncaught Exception: 'ErrorException'With message: 'Division by zero'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(496): Core\Error::errorHandler(2, 'Division by zer...', '/home1/private/...', 496, Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(957): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processeAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processe', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processe')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line496
[19-Jul-2018 01:46:24 Pacific/Pago_Pago] Uncaught Exception: 'LazyJsonMapper\Exception\LazyJsonMapperException'With message: 'Unknown function "getCode".'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(1317): LazyJsonMapper\LazyJsonMapper->__call('getCode', Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(822): App\Controllers\Task->loop_through_medias(Object(InstagramAPI\Instagram), 'usernames', Object(App\Models\Tasks), Array, Array, 200, Array)
#2 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(962): App\Controllers\Task->processfunction()
#3 [internal function]: App\Controllers\Task->processfAction()
#4 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#5 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processf', Array)
#6 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processf')
#7 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/lazyjsonmapper/lazyjsonmapper/src/LazyJsonMapper.php' on line2156
[19-Jul-2018 01:48:04 Pacific/Pago_Pago] Uncaught Exception: 'InvalidArgumentException'With message: 'You must provide a username and password to login().'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(1145): InstagramAPI\Instagram->login(NULL, NULL)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(741): App\Controllers\Task->likeMedia(Object(App\Models\Tasks), '180804303243702...', false)
#2 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(940): App\Controllers\Task->processfunction()
#3 [internal function]: App\Controllers\Task->processbAction()
#4 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#5 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processb', Array)
#6 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processb')
#7 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php' on line441
[19-Jul-2018 01:50:29 Pacific/Pago_Pago] Uncaught Exception: 'Exception'With message: 'No route matched !'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('apple-touch-ico...')
#1 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/Core/Router.php' on line111
[19-Jul-2018 01:50:29 Pacific/Pago_Pago] Uncaught Exception: 'Exception'With message: 'No route matched !'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('apple-touch-ico...')
#1 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/Core/Router.php' on line111
[19-Jul-2018 01:50:30 Pacific/Pago_Pago] Uncaught Exception: 'Exception'With message: 'No route matched !'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('apple-touch-ico...')
#1 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/Core/Router.php' on line111
[19-Jul-2018 01:50:31 Pacific/Pago_Pago] Uncaught Exception: 'Exception'With message: 'No route matched !'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('apple-touch-ico...')
#1 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/Core/Router.php' on line111
[19-Jul-2018 01:50:33 Pacific/Pago_Pago] Uncaught Exception: 'Exception'With message: 'No route matched !'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('apple-touch-ico...')
#1 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/Core/Router.php' on line111
[19-Jul-2018 01:50:34 Pacific/Pago_Pago] Uncaught Exception: 'Exception'With message: 'No route matched !'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('apple-touch-ico...')
#1 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/Core/Router.php' on line111
[19-Jul-2018 01:50:35 Pacific/Pago_Pago] Uncaught Exception: 'Exception'With message: 'No route matched !'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('apple-touch-ico...')
#1 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/Core/Router.php' on line111
[19-Jul-2018 01:50:35 Pacific/Pago_Pago] Uncaught Exception: 'Exception'With message: 'No route matched !'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('apple-touch-ico...')
#1 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/Core/Router.php' on line111
[19-Jul-2018 01:54:00 Pacific/Pago_Pago] Uncaught Exception: 'Exception'With message: 'No route matched !'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('apple-touch-ico...')
#1 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/Core/Router.php' on line111
[19-Jul-2018 01:54:01 Pacific/Pago_Pago] Uncaught Exception: 'Exception'With message: 'No route matched !'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('apple-touch-ico...')
#1 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/Core/Router.php' on line111
[19-Jul-2018 01:57:11 Pacific/Pago_Pago] Uncaught Exception: 'InvalidArgumentException'With message: 'You must provide a username and password to login().'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(1145): InstagramAPI\Instagram->login(NULL, NULL)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(794): App\Controllers\Task->likeMedia(Object(App\Models\Tasks), '180800029350368...', false)
#2 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(952): App\Controllers\Task->processfunction()
#3 [internal function]: App\Controllers\Task->processdAction()
#4 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#5 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processd', Array)
#6 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processd')
#7 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php' on line441
[19-Jul-2018 02:00:03 Pacific/Pago_Pago] Uncaught Exception: 'InvalidArgumentException'With message: 'You must provide a username and password to login().'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(458): InstagramAPI\Instagram->login(NULL, NULL)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(934): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processaAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processa', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processa')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php' on line441
[19-Jul-2018 02:00:06 Pacific/Pago_Pago] Uncaught Exception: 'InvalidArgumentException'With message: 'You must provide a username and password to login().'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(458): InstagramAPI\Instagram->login(NULL, NULL)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(940): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processbAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processb', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processb')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php' on line441
[19-Jul-2018 02:00:13 Pacific/Pago_Pago] Uncaught Exception: 'LazyJsonMapper\Exception\LazyJsonMapperException'With message: 'Unknown function "getCode".'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(1317): LazyJsonMapper\LazyJsonMapper->__call('getCode', Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(822): App\Controllers\Task->loop_through_medias(Object(InstagramAPI\Instagram), 'usernames', Object(App\Models\Tasks), Array, Array, 500, Array)
#2 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(952): App\Controllers\Task->processfunction()
#3 [internal function]: App\Controllers\Task->processdAction()
#4 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#5 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processd', Array)
#6 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processd')
#7 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/lazyjsonmapper/lazyjsonmapper/src/LazyJsonMapper.php' on line2156
[19-Jul-2018 02:00:15 Pacific/Pago_Pago] Uncaught Exception: 'LazyJsonMapper\Exception\LazyJsonMapperException'With message: 'Unknown function "getCode".'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(1317): LazyJsonMapper\LazyJsonMapper->__call('getCode', Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(822): App\Controllers\Task->loop_through_medias(Object(InstagramAPI\Instagram), 'usernames', Object(App\Models\Tasks), Array, Array, 550, Array)
#2 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(946): App\Controllers\Task->processfunction()
#3 [internal function]: App\Controllers\Task->processcAction()
#4 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#5 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processc', Array)
#6 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processc')
#7 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/lazyjsonmapper/lazyjsonmapper/src/LazyJsonMapper.php' on line2156
[19-Jul-2018 02:00:42 Pacific/Pago_Pago] Uncaught Exception: 'InvalidArgumentException'With message: 'Instagram requires that albums contain 2-10 items. You tried to submit 1.'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(1588): InstagramAPI\Request\Timeline->uploadAlbum(Array, Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(40): App\Controllers\Task->postalbum(Array, Array, 'Summer look! ', Array)
#2 [internal function]: App\Controllers\Task->addtaskAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('addtask', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/addtask')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Request/Timeline.php' on line94
[19-Jul-2018 02:20:01 Pacific/Pago_Pago] Uncaught Exception: 'ErrorException'With message: 'Division by zero'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(814): Core\Error::errorHandler(2, 'Division by zer...', '/home1/private/...', 814, Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(934): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processaAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processa', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processa')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line814
[19-Jul-2018 02:23:19 Pacific/Pago_Pago] Uncaught Exception: 'Error'With message: 'Call to undefined method App\Models\Tasks::getRrecordById()'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(668): App\Controllers\Task->add_new_record(Object(App\Models\Tasks), '7216197231', 'chef_meijer')
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(962): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processfAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processf', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processf')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line974
[19-Jul-2018 02:23:21 Pacific/Pago_Pago] Uncaught Exception: 'Error'With message: 'Call to undefined method App\Models\Tasks::getRrecordById()'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(668): App\Controllers\Task->add_new_record(Object(App\Models\Tasks), '7216197231', 'chef_meijer')
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(957): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processeAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processe', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processe')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line974
[19-Jul-2018 02:38:10 Pacific/Pago_Pago] Uncaught Exception: 'ErrorException'With message: 'Division by zero'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(496): Core\Error::errorHandler(2, 'Division by zer...', '/home1/private/...', 496, Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(952): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processdAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processd', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processd')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line496
[19-Jul-2018 02:48:08 Pacific/Pago_Pago] Uncaught Exception: 'InstagramAPI\Exception\ChallengeRequiredException'With message: 'InstagramAPI\Response\LoginResponse: Challenge required.'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Client.php(555): InstagramAPI\Exception\ServerMessageThrower::autoThrow('InstagramAPI\\Re...', 'challenge_requi...', Object(InstagramAPI\Response\LoginResponse), Object(GuzzleHttp\Psr7\Response))
#1 /home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Request.php(793): InstagramAPI\Client->mapServerResponse(Object(InstagramAPI\Response\LoginResponse), '{"message": "ch...', Object(GuzzleHttp\Psr7\Response))
#2 /home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php(496): InstagramAPI\Request->getResponse(Object(InstagramAPI\Response\LoginResponse))
#3 /home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php(444): InstagramAPI\Instagram->_login('meowsme', 'k3kC1yxA', false, 1800)
#4 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(607): InstagramAPI\Instagram->login('meowsme', 'k3kC1yxA')
#5 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(940): App\Controllers\Task->processfunction()
#6 [internal function]: App\Controllers\Task->processbAction()
#7 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#8 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processb', Array)
#9 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processb')
#10 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Exception/ServerMessageThrower.php' on line189
[19-Jul-2018 02:57:11 Pacific/Pago_Pago] Uncaught Exception: 'ErrorException'With message: 'Division by zero'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(709): Core\Error::errorHandler(2, 'Division by zer...', '/home1/private/...', 709, Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(952): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processdAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processd', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processd')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line709
[19-Jul-2018 03:00:09 Pacific/Pago_Pago] Uncaught Exception: 'ErrorException'With message: 'Division by zero'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(496): Core\Error::errorHandler(2, 'Division by zer...', '/home1/private/...', 496, Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(946): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processcAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processc', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processc')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line496
[19-Jul-2018 03:00:14 Pacific/Pago_Pago] Uncaught Exception: 'InvalidArgumentException'With message: 'You must provide a username and password to login().'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(1145): InstagramAPI\Instagram->login(NULL, NULL)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(741): App\Controllers\Task->likeMedia(Object(App\Models\Tasks), '180804303243702...', false)
#2 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(957): App\Controllers\Task->processfunction()
#3 [internal function]: App\Controllers\Task->processeAction()
#4 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#5 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processe', Array)
#6 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processe')
#7 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php' on line441
[19-Jul-2018 03:00:17 Pacific/Pago_Pago] Uncaught Exception: 'InvalidArgumentException'With message: 'You must provide a username and password to login().'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(1145): InstagramAPI\Instagram->login(NULL, NULL)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(794): App\Controllers\Task->likeMedia(Object(App\Models\Tasks), '180800029350368...', false)
#2 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(962): App\Controllers\Task->processfunction()
#3 [internal function]: App\Controllers\Task->processfAction()
#4 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#5 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processf', Array)
#6 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processf')
#7 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php' on line441
[19-Jul-2018 03:00:23 Pacific/Pago_Pago] Uncaught Exception: 'LazyJsonMapper\Exception\LazyJsonMapperException'With message: 'Unknown function "getCode".'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(1317): LazyJsonMapper\LazyJsonMapper->__call('getCode', Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(822): App\Controllers\Task->loop_through_medias(Object(InstagramAPI\Instagram), 'usernames', Object(App\Models\Tasks), Array, Array, 200, Array)
#2 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(952): App\Controllers\Task->processfunction()
#3 [internal function]: App\Controllers\Task->processdAction()
#4 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#5 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processd', Array)
#6 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processd')
#7 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/lazyjsonmapper/lazyjsonmapper/src/LazyJsonMapper.php' on line2156
[19-Jul-2018 03:16:04 Pacific/Pago_Pago] Uncaught Exception: 'InvalidArgumentException'With message: 'You must provide a username and password to login().'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(458): InstagramAPI\Instagram->login(NULL, NULL)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(940): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processbAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processb', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processb')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php' on line441
[19-Jul-2018 03:19:10 Pacific/Pago_Pago] Uncaught Exception: 'InvalidArgumentException'With message: 'You must provide a username and password to login().'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(458): InstagramAPI\Instagram->login(NULL, NULL)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(952): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processdAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processd', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processd')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php' on line441
[19-Jul-2018 03:20:11 Pacific/Pago_Pago] Uncaught Exception: 'LazyJsonMapper\Exception\LazyJsonMapperException'With message: 'Unknown function "getCode".'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(1317): LazyJsonMapper\LazyJsonMapper->__call('getCode', Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(822): App\Controllers\Task->loop_through_medias(Object(InstagramAPI\Instagram), 'usernames', Object(App\Models\Tasks), Array, Array, 550, Array)
#2 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(934): App\Controllers\Task->processfunction()
#3 [internal function]: App\Controllers\Task->processaAction()
#4 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#5 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processa', Array)
#6 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processa')
#7 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/lazyjsonmapper/lazyjsonmapper/src/LazyJsonMapper.php' on line2156
[19-Jul-2018 03:22:10 Pacific/Pago_Pago] Uncaught Exception: 'LazyJsonMapper\Exception\LazyJsonMapperException'With message: 'Unknown function "getCode".'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(1317): LazyJsonMapper\LazyJsonMapper->__call('getCode', Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(822): App\Controllers\Task->loop_through_medias(Object(InstagramAPI\Instagram), 'usernames', Object(App\Models\Tasks), Array, Array, 500, Array)
#2 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(946): App\Controllers\Task->processfunction()
#3 [internal function]: App\Controllers\Task->processcAction()
#4 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#5 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processc', Array)
#6 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processc')
#7 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/lazyjsonmapper/lazyjsonmapper/src/LazyJsonMapper.php' on line2156
[19-Jul-2018 03:40:01 Pacific/Pago_Pago] Uncaught Exception: 'ErrorException'With message: 'Division by zero'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(814): Core\Error::errorHandler(2, 'Division by zer...', '/home1/private/...', 814, Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(934): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processaAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processa', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processa')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line814
[19-Jul-2018 03:46:19 Pacific/Pago_Pago] Uncaught Exception: 'Error'With message: 'Call to undefined method App\Models\Tasks::getRrecordById()'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(668): App\Controllers\Task->add_new_record(Object(App\Models\Tasks), '7216197231', 'chef_meijer')
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(962): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processfAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processf', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processf')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line974
[19-Jul-2018 03:46:22 Pacific/Pago_Pago] Uncaught Exception: 'Error'With message: 'Call to undefined method App\Models\Tasks::getRrecordById()'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(668): App\Controllers\Task->add_new_record(Object(App\Models\Tasks), '7216197231', 'chef_meijer')
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(957): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processeAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processe', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processe')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line974
[19-Jul-2018 03:57:10 Pacific/Pago_Pago] Uncaught Exception: 'ErrorException'With message: 'Division by zero'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(496): Core\Error::errorHandler(2, 'Division by zer...', '/home1/private/...', 496, Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(952): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processdAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processd', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processd')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line496
[19-Jul-2018 04:00:18 Pacific/Pago_Pago] Uncaught Exception: 'InstagramAPI\Exception\ChallengeRequiredException'With message: 'InstagramAPI\Response\LoginResponse: Challenge required.'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Client.php(555): InstagramAPI\Exception\ServerMessageThrower::autoThrow('InstagramAPI\\Re...', 'challenge_requi...', Object(InstagramAPI\Response\LoginResponse), Object(GuzzleHttp\Psr7\Response))
#1 /home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Request.php(793): InstagramAPI\Client->mapServerResponse(Object(InstagramAPI\Response\LoginResponse), '{"message": "ch...', Object(GuzzleHttp\Psr7\Response))
#2 /home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php(496): InstagramAPI\Request->getResponse(Object(InstagramAPI\Response\LoginResponse))
#3 /home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php(444): InstagramAPI\Instagram->_login('meowsme', 'k3kC1yxA', false, 1800)
#4 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(607): InstagramAPI\Instagram->login('meowsme', 'k3kC1yxA')
#5 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(957): App\Controllers\Task->processfunction()
#6 [internal function]: App\Controllers\Task->processeAction()
#7 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#8 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processe', Array)
#9 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processe')
#10 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Exception/ServerMessageThrower.php' on line189
[19-Jul-2018 04:00:18 Pacific/Pago_Pago] Uncaught Exception: 'ErrorException'With message: 'Division by zero'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(709): Core\Error::errorHandler(2, 'Division by zer...', '/home1/private/...', 709, Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(962): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processfAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processf', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processf')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line709
[19-Jul-2018 04:20:02 Pacific/Pago_Pago] Uncaught Exception: 'ErrorException'With message: 'Division by zero'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(496): Core\Error::errorHandler(2, 'Division by zer...', '/home1/private/...', 496, Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(934): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processaAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processa', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processa')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line496
[19-Jul-2018 04:22:16 Pacific/Pago_Pago] Uncaught Exception: 'LazyJsonMapper\Exception\LazyJsonMapperException'With message: 'Unknown function "getCode".'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(1317): LazyJsonMapper\LazyJsonMapper->__call('getCode', Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(822): App\Controllers\Task->loop_through_medias(Object(InstagramAPI\Instagram), 'usernames', Object(App\Models\Tasks), Array, Array, 200, Array)
#2 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(946): App\Controllers\Task->processfunction()
#3 [internal function]: App\Controllers\Task->processcAction()
#4 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#5 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processc', Array)
#6 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processc')
#7 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/lazyjsonmapper/lazyjsonmapper/src/LazyJsonMapper.php' on line2156
[19-Jul-2018 04:23:13 Pacific/Pago_Pago] Uncaught Exception: 'InvalidArgumentException'With message: 'You must provide a username and password to login().'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(1145): InstagramAPI\Instagram->login(NULL, NULL)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(741): App\Controllers\Task->likeMedia(Object(App\Models\Tasks), '180804303243702...', false)
#2 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(957): App\Controllers\Task->processfunction()
#3 [internal function]: App\Controllers\Task->processeAction()
#4 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#5 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processe', Array)
#6 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processe')
#7 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php' on line441
[19-Jul-2018 04:23:16 Pacific/Pago_Pago] Uncaught Exception: 'InvalidArgumentException'With message: 'You must provide a username and password to login().'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(1145): InstagramAPI\Instagram->login(NULL, NULL)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(794): App\Controllers\Task->likeMedia(Object(App\Models\Tasks), '180800029350368...', false)
#2 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(962): App\Controllers\Task->processfunction()
#3 [internal function]: App\Controllers\Task->processfAction()
#4 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#5 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processf', Array)
#6 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processf')
#7 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php' on line441
[19-Jul-2018 04:32:05 Pacific/Pago_Pago] Uncaught Exception: 'InvalidArgumentException'With message: 'You must provide a username and password to login().'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(458): InstagramAPI\Instagram->login(NULL, NULL)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(940): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processbAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processb', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processb')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php' on line441
[19-Jul-2018 04:38:11 Pacific/Pago_Pago] Uncaught Exception: 'InvalidArgumentException'With message: 'You must provide a username and password to login().'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(458): InstagramAPI\Instagram->login(NULL, NULL)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(952): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processdAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processd', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processd')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php' on line441
[19-Jul-2018 04:40:09 Pacific/Pago_Pago] Uncaught Exception: 'LazyJsonMapper\Exception\LazyJsonMapperException'With message: 'Unknown function "getCode".'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(1317): LazyJsonMapper\LazyJsonMapper->__call('getCode', Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(822): App\Controllers\Task->loop_through_medias(Object(InstagramAPI\Instagram), 'usernames', Object(App\Models\Tasks), Array, Array, 550, Array)
#2 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(934): App\Controllers\Task->processfunction()
#3 [internal function]: App\Controllers\Task->processaAction()
#4 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#5 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processa', Array)
#6 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processa')
#7 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/lazyjsonmapper/lazyjsonmapper/src/LazyJsonMapper.php' on line2156
[19-Jul-2018 04:44:10 Pacific/Pago_Pago] Uncaught Exception: 'LazyJsonMapper\Exception\LazyJsonMapperException'With message: 'Unknown function "getCode".'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(1317): LazyJsonMapper\LazyJsonMapper->__call('getCode', Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(822): App\Controllers\Task->loop_through_medias(Object(InstagramAPI\Instagram), 'usernames', Object(App\Models\Tasks), Array, Array, 500, Array)
#2 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(946): App\Controllers\Task->processfunction()
#3 [internal function]: App\Controllers\Task->processcAction()
#4 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#5 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processc', Array)
#6 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processc')
#7 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/lazyjsonmapper/lazyjsonmapper/src/LazyJsonMapper.php' on line2156
[19-Jul-2018 05:00:02 Pacific/Pago_Pago] Uncaught Exception: 'ErrorException'With message: 'Division by zero'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(814): Core\Error::errorHandler(2, 'Division by zer...', '/home1/private/...', 814, Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(934): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processaAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processa', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processa')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line814
[19-Jul-2018 05:00:17 Pacific/Pago_Pago] Uncaught Exception: 'ErrorException'With message: 'Division by zero'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(496): Core\Error::errorHandler(2, 'Division by zer...', '/home1/private/...', 496, Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(962): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processfAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processf', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processf')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line496
[19-Jul-2018 05:00:31 Pacific/Pago_Pago] Uncaught Exception: 'Error'With message: 'Call to undefined method App\Models\Tasks::getRrecordById()'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(668): App\Controllers\Task->add_new_record(Object(App\Models\Tasks), '7216197231', 'chef_meijer')
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(946): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processcAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processc', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processc')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line974
[19-Jul-2018 05:00:31 Pacific/Pago_Pago] Uncaught Exception: 'Error'With message: 'Call to undefined method App\Models\Tasks::getRrecordById()'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(668): App\Controllers\Task->add_new_record(Object(App\Models\Tasks), '7216197231', 'chef_meijer')
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(952): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processdAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processd', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processd')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line974
[19-Jul-2018 05:23:15 Pacific/Pago_Pago] Uncaught Exception: 'InstagramAPI\Exception\ChallengeRequiredException'With message: 'InstagramAPI\Response\LoginResponse: Challenge required.'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Client.php(555): InstagramAPI\Exception\ServerMessageThrower::autoThrow('InstagramAPI\\Re...', 'challenge_requi...', Object(InstagramAPI\Response\LoginResponse), Object(GuzzleHttp\Psr7\Response))
#1 /home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Request.php(793): InstagramAPI\Client->mapServerResponse(Object(InstagramAPI\Response\LoginResponse), '{"message": "ch...', Object(GuzzleHttp\Psr7\Response))
#2 /home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php(496): InstagramAPI\Request->getResponse(Object(InstagramAPI\Response\LoginResponse))
#3 /home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php(444): InstagramAPI\Instagram->_login('meowsme', 'k3kC1yxA', false, 1800)
#4 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(607): InstagramAPI\Instagram->login('meowsme', 'k3kC1yxA')
#5 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(957): App\Controllers\Task->processfunction()
#6 [internal function]: App\Controllers\Task->processeAction()
#7 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#8 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processe', Array)
#9 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processe')
#10 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Exception/ServerMessageThrower.php' on line189
[19-Jul-2018 05:23:16 Pacific/Pago_Pago] Uncaught Exception: 'ErrorException'With message: 'Division by zero'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(709): Core\Error::errorHandler(2, 'Division by zer...', '/home1/private/...', 709, Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(962): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processfAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processf', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processf')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line709
[19-Jul-2018 05:40:01 Pacific/Pago_Pago] Uncaught Exception: 'ErrorException'With message: 'Division by zero'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(496): Core\Error::errorHandler(2, 'Division by zer...', '/home1/private/...', 496, Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(934): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processaAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processa', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processa')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line496
[19-Jul-2018 05:44:16 Pacific/Pago_Pago] Uncaught Exception: 'LazyJsonMapper\Exception\LazyJsonMapperException'With message: 'Unknown function "getCode".'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(1317): LazyJsonMapper\LazyJsonMapper->__call('getCode', Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(822): App\Controllers\Task->loop_through_medias(Object(InstagramAPI\Instagram), 'usernames', Object(App\Models\Tasks), Array, Array, 200, Array)
#2 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(946): App\Controllers\Task->processfunction()
#3 [internal function]: App\Controllers\Task->processcAction()
#4 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#5 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processc', Array)
#6 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processc')
#7 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/lazyjsonmapper/lazyjsonmapper/src/LazyJsonMapper.php' on line2156
[19-Jul-2018 05:46:13 Pacific/Pago_Pago] Uncaught Exception: 'InvalidArgumentException'With message: 'You must provide a username and password to login().'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(1145): InstagramAPI\Instagram->login(NULL, NULL)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(741): App\Controllers\Task->likeMedia(Object(App\Models\Tasks), '180804303243702...', false)
#2 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(957): App\Controllers\Task->processfunction()
#3 [internal function]: App\Controllers\Task->processeAction()
#4 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#5 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processe', Array)
#6 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processe')
#7 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php' on line441
[19-Jul-2018 05:46:16 Pacific/Pago_Pago] Uncaught Exception: 'InvalidArgumentException'With message: 'You must provide a username and password to login().'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(1145): InstagramAPI\Instagram->login(NULL, NULL)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(794): App\Controllers\Task->likeMedia(Object(App\Models\Tasks), '180800029350368...', false)
#2 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(962): App\Controllers\Task->processfunction()
#3 [internal function]: App\Controllers\Task->processfAction()
#4 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#5 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processf', Array)
#6 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processf')
#7 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php' on line441
[19-Jul-2018 05:48:04 Pacific/Pago_Pago] Uncaught Exception: 'InvalidArgumentException'With message: 'You must provide a username and password to login().'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(458): InstagramAPI\Instagram->login(NULL, NULL)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(940): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processbAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processb', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processb')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php' on line441
[19-Jul-2018 05:57:11 Pacific/Pago_Pago] Uncaught Exception: 'InvalidArgumentException'With message: 'You must provide a username and password to login().'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(458): InstagramAPI\Instagram->login(NULL, NULL)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(952): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processdAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processd', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processd')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php' on line441
[19-Jul-2018 06:00:16 Pacific/Pago_Pago] Uncaught Exception: 'LazyJsonMapper\Exception\LazyJsonMapperException'With message: 'Unknown function "getCode".'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(1317): LazyJsonMapper\LazyJsonMapper->__call('getCode', Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(822): App\Controllers\Task->loop_through_medias(Object(InstagramAPI\Instagram), 'usernames', Object(App\Models\Tasks), Array, Array, 500, Array)
#2 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(940): App\Controllers\Task->processfunction()
#3 [internal function]: App\Controllers\Task->processbAction()
#4 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#5 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processb', Array)
#6 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processb')
#7 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/lazyjsonmapper/lazyjsonmapper/src/LazyJsonMapper.php' on line2156
[19-Jul-2018 06:00:16 Pacific/Pago_Pago] Uncaught Exception: 'LazyJsonMapper\Exception\LazyJsonMapperException'With message: 'Unknown function "getCode".'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(1317): LazyJsonMapper\LazyJsonMapper->__call('getCode', Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(822): App\Controllers\Task->loop_through_medias(Object(InstagramAPI\Instagram), 'usernames', Object(App\Models\Tasks), Array, Array, 550, Array)
#2 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(934): App\Controllers\Task->processfunction()
#3 [internal function]: App\Controllers\Task->processaAction()
#4 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#5 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processa', Array)
#6 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processa')
#7 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/lazyjsonmapper/lazyjsonmapper/src/LazyJsonMapper.php' on line2156
[19-Jul-2018 06:00:16 Pacific/Pago_Pago] PHP Fatal error:  Uncaught InstagramAPI\Exception\SettingsException: The "/home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/sessions/dy_zvd/dy_zvd-cookies.dat" cookie file is not writable. in /home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Settings/StorageHandler.php:507
Stack trace:
#0 /home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Client.php(305): InstagramAPI\Settings\StorageHandler->setCookies('[{"Name":"mid",...')
#1 /home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php(307): InstagramAPI\Client->saveCookieJar()
#2 /home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Settings/StorageHandler.php(612): InstagramAPI\Instagram->InstagramAPI\{closure}(Object(InstagramAPI\Settings\StorageHandler))
#3 /home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Settings/StorageHandler.php(154): InstagramAPI\Settings\StorageHandler->_triggerCallback('onCloseUser')
#4 [internal function]: InstagramAPI\Settings in /home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Settings/StorageHandler.php on line 507
[19-Jul-2018 06:16:05 Pacific/Pago_Pago] Uncaught Exception: 'ErrorException'With message: 'Division by zero'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(814): Core\Error::errorHandler(2, 'Division by zer...', '/home1/private/...', 814, Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(940): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processbAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processb', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processb')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line814
[19-Jul-2018 06:20:10 Pacific/Pago_Pago] Uncaught Exception: 'Error'With message: 'Call to undefined method App\Models\Tasks::getRrecordById()'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(668): App\Controllers\Task->add_new_record(Object(App\Models\Tasks), '7216197231', 'chef_meijer')
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(934): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processaAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processa', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processa')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line974
[19-Jul-2018 06:22:10 Pacific/Pago_Pago] Uncaught Exception: 'Error'With message: 'Call to undefined method App\Models\Tasks::getRrecordById()'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(668): App\Controllers\Task->add_new_record(Object(App\Models\Tasks), '7216197231', 'chef_meijer')
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(946): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processcAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processc', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processc')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line974
[19-Jul-2018 06:23:16 Pacific/Pago_Pago] Uncaught Exception: 'ErrorException'With message: 'Division by zero'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(496): Core\Error::errorHandler(2, 'Division by zer...', '/home1/private/...', 496, Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(962): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processfAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processf', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processf')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line496
[19-Jul-2018 06:46:16 Pacific/Pago_Pago] Uncaught Exception: 'InstagramAPI\Exception\ChallengeRequiredException'With message: 'InstagramAPI\Response\LoginResponse: Challenge required.'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Client.php(555): InstagramAPI\Exception\ServerMessageThrower::autoThrow('InstagramAPI\\Re...', 'challenge_requi...', Object(InstagramAPI\Response\LoginResponse), Object(GuzzleHttp\Psr7\Response))
#1 /home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Request.php(793): InstagramAPI\Client->mapServerResponse(Object(InstagramAPI\Response\LoginResponse), '{"message": "ch...', Object(GuzzleHttp\Psr7\Response))
#2 /home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php(496): InstagramAPI\Request->getResponse(Object(InstagramAPI\Response\LoginResponse))
#3 /home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php(444): InstagramAPI\Instagram->_login('meowsme', 'k3kC1yxA', false, 1800)
#4 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(607): InstagramAPI\Instagram->login('meowsme', 'k3kC1yxA')
#5 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(957): App\Controllers\Task->processfunction()
#6 [internal function]: App\Controllers\Task->processeAction()
#7 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#8 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processe', Array)
#9 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processe')
#10 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Exception/ServerMessageThrower.php' on line189
[19-Jul-2018 06:46:16 Pacific/Pago_Pago] Uncaught Exception: 'ErrorException'With message: 'Division by zero'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(709): Core\Error::errorHandler(2, 'Division by zer...', '/home1/private/...', 709, Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(962): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processfAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processf', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processf')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line709
[19-Jul-2018 07:00:02 Pacific/Pago_Pago] Uncaught Exception: 'ErrorException'With message: 'Division by zero'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(496): Core\Error::errorHandler(2, 'Division by zer...', '/home1/private/...', 496, Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(934): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processaAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processa', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processa')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line496
[19-Jul-2018 07:00:08 Pacific/Pago_Pago] Uncaught Exception: 'InvalidArgumentException'With message: 'You must provide a username and password to login().'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(1145): InstagramAPI\Instagram->login(NULL, NULL)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(741): App\Controllers\Task->likeMedia(Object(App\Models\Tasks), '180804303243702...', false)
#2 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(946): App\Controllers\Task->processfunction()
#3 [internal function]: App\Controllers\Task->processcAction()
#4 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#5 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processc', Array)
#6 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processc')
#7 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php' on line441
[19-Jul-2018 07:00:11 Pacific/Pago_Pago] Uncaught Exception: 'InvalidArgumentException'With message: 'You must provide a username and password to login().'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(1145): InstagramAPI\Instagram->login(NULL, NULL)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(794): App\Controllers\Task->likeMedia(Object(App\Models\Tasks), '180800029350368...', false)
#2 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(952): App\Controllers\Task->processfunction()
#3 [internal function]: App\Controllers\Task->processdAction()
#4 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#5 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processd', Array)
#6 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processd')
#7 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php' on line441
[19-Jul-2018 07:00:14 Pacific/Pago_Pago] Uncaught Exception: 'InvalidArgumentException'With message: 'You must provide a username and password to login().'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(458): InstagramAPI\Instagram->login(NULL, NULL)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(957): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processeAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processe', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processe')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php' on line441
[19-Jul-2018 07:00:17 Pacific/Pago_Pago] Uncaught Exception: 'InvalidArgumentException'With message: 'You must provide a username and password to login().'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(458): InstagramAPI\Instagram->login(NULL, NULL)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(962): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processfAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processf', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processf')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php' on line441
[19-Jul-2018 07:00:19 Pacific/Pago_Pago] Uncaught Exception: 'LazyJsonMapper\Exception\LazyJsonMapperException'With message: 'Unknown function "getCode".'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(1317): LazyJsonMapper\LazyJsonMapper->__call('getCode', Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(822): App\Controllers\Task->loop_through_medias(Object(InstagramAPI\Instagram), 'usernames', Object(App\Models\Tasks), Array, Array, 200, Array)
#2 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(940): App\Controllers\Task->processfunction()
#3 [internal function]: App\Controllers\Task->processbAction()
#4 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#5 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processb', Array)
#6 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processb')
#7 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/lazyjsonmapper/lazyjsonmapper/src/LazyJsonMapper.php' on line2156
[19-Jul-2018 07:16:13 Pacific/Pago_Pago] Uncaught Exception: 'LazyJsonMapper\Exception\LazyJsonMapperException'With message: 'Unknown function "getCode".'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(1317): LazyJsonMapper\LazyJsonMapper->__call('getCode', Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(822): App\Controllers\Task->loop_through_medias(Object(InstagramAPI\Instagram), 'usernames', Object(App\Models\Tasks), Array, Array, 550, Array)
#2 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(940): App\Controllers\Task->processfunction()
#3 [internal function]: App\Controllers\Task->processbAction()
#4 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#5 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processb', Array)
#6 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processb')
#7 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/lazyjsonmapper/lazyjsonmapper/src/LazyJsonMapper.php' on line2156
[19-Jul-2018 07:19:14 Pacific/Pago_Pago] Uncaught Exception: 'LazyJsonMapper\Exception\LazyJsonMapperException'With message: 'Unknown function "getCode".'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(1317): LazyJsonMapper\LazyJsonMapper->__call('getCode', Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(822): App\Controllers\Task->loop_through_medias(Object(InstagramAPI\Instagram), 'usernames', Object(App\Models\Tasks), Array, Array, 500, Array)
#2 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(952): App\Controllers\Task->processfunction()
#3 [internal function]: App\Controllers\Task->processdAction()
#4 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#5 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processd', Array)
#6 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processd')
#7 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/lazyjsonmapper/lazyjsonmapper/src/LazyJsonMapper.php' on line2156
[19-Jul-2018 07:32:04 Pacific/Pago_Pago] Uncaught Exception: 'ErrorException'With message: 'Division by zero'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(814): Core\Error::errorHandler(2, 'Division by zer...', '/home1/private/...', 814, Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(940): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processbAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processb', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processb')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line814
[19-Jul-2018 07:40:10 Pacific/Pago_Pago] Uncaught Exception: 'Error'With message: 'Call to undefined method App\Models\Tasks::getRrecordById()'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(668): App\Controllers\Task->add_new_record(Object(App\Models\Tasks), '7216197231', 'chef_meijer')
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(934): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processaAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processa', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processa')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line974
[19-Jul-2018 07:44:11 Pacific/Pago_Pago] Uncaught Exception: 'Error'With message: 'Call to undefined method App\Models\Tasks::getRrecordById()'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(668): App\Controllers\Task->add_new_record(Object(App\Models\Tasks), '7216197231', 'chef_meijer')
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(946): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processcAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processc', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processc')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line974
[19-Jul-2018 07:46:16 Pacific/Pago_Pago] Uncaught Exception: 'ErrorException'With message: 'Division by zero'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(496): Core\Error::errorHandler(2, 'Division by zer...', '/home1/private/...', 496, Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(962): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processfAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processf', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processf')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line496
[19-Jul-2018 07:48:49 Pacific/Pago_Pago] Uncaught Exception: 'Exception'With message: 'No route matched !'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('robots.txt')
#1 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/Core/Router.php' on line111
[19-Jul-2018 08:00:12 Pacific/Pago_Pago] Uncaught Exception: 'ErrorException'With message: 'Division by zero'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(709): Core\Error::errorHandler(2, 'Division by zer...', '/home1/private/...', 709, Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(952): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processdAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processd', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processd')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line709
[19-Jul-2018 08:00:15 Pacific/Pago_Pago] Uncaught Exception: 'InstagramAPI\Exception\ChallengeRequiredException'With message: 'InstagramAPI\Response\LoginResponse: Challenge required.'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Client.php(555): InstagramAPI\Exception\ServerMessageThrower::autoThrow('InstagramAPI\\Re...', 'challenge_requi...', Object(InstagramAPI\Response\LoginResponse), Object(GuzzleHttp\Psr7\Response))
#1 /home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Request.php(793): InstagramAPI\Client->mapServerResponse(Object(InstagramAPI\Response\LoginResponse), '{"message": "ch...', Object(GuzzleHttp\Psr7\Response))
#2 /home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php(496): InstagramAPI\Request->getResponse(Object(InstagramAPI\Response\LoginResponse))
#3 /home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php(444): InstagramAPI\Instagram->_login('meowsme', 'k3kC1yxA', false, 1800)
#4 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(607): InstagramAPI\Instagram->login('meowsme', 'k3kC1yxA')
#5 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(946): App\Controllers\Task->processfunction()
#6 [internal function]: App\Controllers\Task->processcAction()
#7 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#8 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processc', Array)
#9 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processc')
#10 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Exception/ServerMessageThrower.php' on line189
[19-Jul-2018 08:16:04 Pacific/Pago_Pago] Uncaught Exception: 'ErrorException'With message: 'Division by zero'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(496): Core\Error::errorHandler(2, 'Division by zer...', '/home1/private/...', 496, Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(940): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processbAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processb', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processb')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line496
[19-Jul-2018 08:19:18 Pacific/Pago_Pago] Uncaught Exception: 'LazyJsonMapper\Exception\LazyJsonMapperException'With message: 'Unknown function "getCode".'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(1317): LazyJsonMapper\LazyJsonMapper->__call('getCode', Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(822): App\Controllers\Task->loop_through_medias(Object(InstagramAPI\Instagram), 'usernames', Object(App\Models\Tasks), Array, Array, 200, Array)
#2 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(952): App\Controllers\Task->processfunction()
#3 [internal function]: App\Controllers\Task->processdAction()
#4 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#5 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processd', Array)
#6 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processd')
#7 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/lazyjsonmapper/lazyjsonmapper/src/LazyJsonMapper.php' on line2156
[19-Jul-2018 08:20:02 Pacific/Pago_Pago] Uncaught Exception: 'InvalidArgumentException'With message: 'You must provide a username and password to login().'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(1145): InstagramAPI\Instagram->login(NULL, NULL)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(741): App\Controllers\Task->likeMedia(Object(App\Models\Tasks), '180804303243702...', false)
#2 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(934): App\Controllers\Task->processfunction()
#3 [internal function]: App\Controllers\Task->processaAction()
#4 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#5 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processa', Array)
#6 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processa')
#7 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php' on line441
[19-Jul-2018 08:22:08 Pacific/Pago_Pago] Uncaught Exception: 'InvalidArgumentException'With message: 'You must provide a username and password to login().'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(1145): InstagramAPI\Instagram->login(NULL, NULL)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(794): App\Controllers\Task->likeMedia(Object(App\Models\Tasks), '180800029350368...', false)
#2 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(946): App\Controllers\Task->processfunction()
#3 [internal function]: App\Controllers\Task->processcAction()
#4 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#5 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processc', Array)
#6 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processc')
#7 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php' on line441
[19-Jul-2018 08:23:14 Pacific/Pago_Pago] Uncaught Exception: 'InvalidArgumentException'With message: 'You must provide a username and password to login().'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(458): InstagramAPI\Instagram->login(NULL, NULL)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(957): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processeAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processe', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processe')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php' on line441
[19-Jul-2018 08:23:17 Pacific/Pago_Pago] Uncaught Exception: 'InvalidArgumentException'With message: 'You must provide a username and password to login().'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(458): InstagramAPI\Instagram->login(NULL, NULL)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(962): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processfAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processf', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processf')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php' on line441
[19-Jul-2018 08:32:13 Pacific/Pago_Pago] Uncaught Exception: 'LazyJsonMapper\Exception\LazyJsonMapperException'With message: 'Unknown function "getCode".'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(1317): LazyJsonMapper\LazyJsonMapper->__call('getCode', Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(822): App\Controllers\Task->loop_through_medias(Object(InstagramAPI\Instagram), 'usernames', Object(App\Models\Tasks), Array, Array, 550, Array)
#2 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(940): App\Controllers\Task->processfunction()
#3 [internal function]: App\Controllers\Task->processbAction()
#4 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#5 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processb', Array)
#6 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processb')
#7 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/lazyjsonmapper/lazyjsonmapper/src/LazyJsonMapper.php' on line2156
[19-Jul-2018 08:38:14 Pacific/Pago_Pago] Uncaught Exception: 'LazyJsonMapper\Exception\LazyJsonMapperException'With message: 'Unknown function "getCode".'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(1317): LazyJsonMapper\LazyJsonMapper->__call('getCode', Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(822): App\Controllers\Task->loop_through_medias(Object(InstagramAPI\Instagram), 'usernames', Object(App\Models\Tasks), Array, Array, 500, Array)
#2 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(952): App\Controllers\Task->processfunction()
#3 [internal function]: App\Controllers\Task->processdAction()
#4 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#5 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processd', Array)
#6 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processd')
#7 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/lazyjsonmapper/lazyjsonmapper/src/LazyJsonMapper.php' on line2156
[19-Jul-2018 08:43:35 Pacific/Pago_Pago] Uncaught Exception: 'Exception'With message: 'No route matched !'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('robots.txt')
#1 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/Core/Router.php' on line111
[19-Jul-2018 08:48:04 Pacific/Pago_Pago] Uncaught Exception: 'ErrorException'With message: 'Division by zero'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(814): Core\Error::errorHandler(2, 'Division by zer...', '/home1/private/...', 814, Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(940): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processbAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processb', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processb')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line814
[19-Jul-2018 09:00:08 Pacific/Pago_Pago] Uncaught Exception: 'Error'With message: 'Call to undefined method App\Models\Tasks::getRrecordById()'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(668): App\Controllers\Task->add_new_record(Object(App\Models\Tasks), '7216197231', 'chef_meijer')
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(940): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processbAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processb', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processb')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line974
[19-Jul-2018 09:00:11 Pacific/Pago_Pago] Uncaught Exception: 'ErrorException'With message: 'Division by zero'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(496): Core\Error::errorHandler(2, 'Division by zer...', '/home1/private/...', 496, Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(952): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processdAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processd', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processd')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line496
[19-Jul-2018 09:00:12 Pacific/Pago_Pago] Uncaught Exception: 'Error'With message: 'Call to undefined method App\Models\Tasks::getRrecordById()'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(668): App\Controllers\Task->add_new_record(Object(App\Models\Tasks), '7216197231', 'chef_meijer')
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(934): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processaAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processa', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processa')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line974
[19-Jul-2018 09:20:04 Pacific/Pago_Pago] Uncaught Exception: 'InstagramAPI\Exception\ChallengeRequiredException'With message: 'InstagramAPI\Response\LoginResponse: Challenge required.'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Client.php(555): InstagramAPI\Exception\ServerMessageThrower::autoThrow('InstagramAPI\\Re...', 'challenge_requi...', Object(InstagramAPI\Response\LoginResponse), Object(GuzzleHttp\Psr7\Response))
#1 /home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Request.php(793): InstagramAPI\Client->mapServerResponse(Object(InstagramAPI\Response\LoginResponse), '{"message": "ch...', Object(GuzzleHttp\Psr7\Response))
#2 /home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php(496): InstagramAPI\Request->getResponse(Object(InstagramAPI\Response\LoginResponse))
#3 /home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php(444): InstagramAPI\Instagram->_login('meowsme', 'k3kC1yxA', false, 1800)
#4 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(607): InstagramAPI\Instagram->login('meowsme', 'k3kC1yxA')
#5 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(934): App\Controllers\Task->processfunction()
#6 [internal function]: App\Controllers\Task->processaAction()
#7 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#8 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processa', Array)
#9 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processa')
#10 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Exception/ServerMessageThrower.php' on line189
[19-Jul-2018 09:22:07 Pacific/Pago_Pago] Uncaught Exception: 'ErrorException'With message: 'Division by zero'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(709): Core\Error::errorHandler(2, 'Division by zer...', '/home1/private/...', 709, Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(946): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processcAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processc', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processc')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line709
[19-Jul-2018 09:32:05 Pacific/Pago_Pago] Uncaught Exception: 'ErrorException'With message: 'Division by zero'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(496): Core\Error::errorHandler(2, 'Division by zer...', '/home1/private/...', 496, Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(940): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processbAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processb', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processb')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line496
[19-Jul-2018 09:38:18 Pacific/Pago_Pago] Uncaught Exception: 'LazyJsonMapper\Exception\LazyJsonMapperException'With message: 'Unknown function "getCode".'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(1317): LazyJsonMapper\LazyJsonMapper->__call('getCode', Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(822): App\Controllers\Task->loop_through_medias(Object(InstagramAPI\Instagram), 'usernames', Object(App\Models\Tasks), Array, Array, 200, Array)
#2 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(952): App\Controllers\Task->processfunction()
#3 [internal function]: App\Controllers\Task->processdAction()
#4 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#5 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processd', Array)
#6 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processd')
#7 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/lazyjsonmapper/lazyjsonmapper/src/LazyJsonMapper.php' on line2156
[19-Jul-2018 09:40:02 Pacific/Pago_Pago] Uncaught Exception: 'InvalidArgumentException'With message: 'You must provide a username and password to login().'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(1145): InstagramAPI\Instagram->login(NULL, NULL)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(741): App\Controllers\Task->likeMedia(Object(App\Models\Tasks), '180804303243702...', false)
#2 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(934): App\Controllers\Task->processfunction()
#3 [internal function]: App\Controllers\Task->processaAction()
#4 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#5 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processa', Array)
#6 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processa')
#7 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php' on line441
[19-Jul-2018 09:44:08 Pacific/Pago_Pago] Uncaught Exception: 'InvalidArgumentException'With message: 'You must provide a username and password to login().'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(1145): InstagramAPI\Instagram->login(NULL, NULL)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(794): App\Controllers\Task->likeMedia(Object(App\Models\Tasks), '180800029350368...', false)
#2 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(946): App\Controllers\Task->processfunction()
#3 [internal function]: App\Controllers\Task->processcAction()
#4 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#5 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processc', Array)
#6 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processc')
#7 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php' on line441
[19-Jul-2018 09:46:13 Pacific/Pago_Pago] Uncaught Exception: 'InvalidArgumentException'With message: 'You must provide a username and password to login().'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(458): InstagramAPI\Instagram->login(NULL, NULL)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(957): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processeAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processe', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processe')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php' on line441
[19-Jul-2018 09:46:16 Pacific/Pago_Pago] Uncaught Exception: 'InvalidArgumentException'With message: 'You must provide a username and password to login().'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(458): InstagramAPI\Instagram->login(NULL, NULL)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(962): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processfAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processf', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processf')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php' on line441
[19-Jul-2018 09:48:12 Pacific/Pago_Pago] Uncaught Exception: 'LazyJsonMapper\Exception\LazyJsonMapperException'With message: 'Unknown function "getCode".'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(1317): LazyJsonMapper\LazyJsonMapper->__call('getCode', Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(822): App\Controllers\Task->loop_through_medias(Object(InstagramAPI\Instagram), 'usernames', Object(App\Models\Tasks), Array, Array, 550, Array)
#2 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(940): App\Controllers\Task->processfunction()
#3 [internal function]: App\Controllers\Task->processbAction()
#4 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#5 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processb', Array)
#6 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processb')
#7 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/lazyjsonmapper/lazyjsonmapper/src/LazyJsonMapper.php' on line2156
[19-Jul-2018 09:57:13 Pacific/Pago_Pago] Uncaught Exception: 'LazyJsonMapper\Exception\LazyJsonMapperException'With message: 'Unknown function "getCode".'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(1317): LazyJsonMapper\LazyJsonMapper->__call('getCode', Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(822): App\Controllers\Task->loop_through_medias(Object(InstagramAPI\Instagram), 'usernames', Object(App\Models\Tasks), Array, Array, 500, Array)
#2 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(952): App\Controllers\Task->processfunction()
#3 [internal function]: App\Controllers\Task->processdAction()
#4 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#5 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processd', Array)
#6 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processd')
#7 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/lazyjsonmapper/lazyjsonmapper/src/LazyJsonMapper.php' on line2156
[19-Jul-2018 10:00:14 Pacific/Pago_Pago] Uncaught Exception: 'ErrorException'With message: 'Division by zero'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(814): Core\Error::errorHandler(2, 'Division by zer...', '/home1/private/...', 814, Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(957): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processeAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processe', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processe')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line814
[19-Jul-2018 10:16:14 Pacific/Pago_Pago] Uncaught Exception: 'Error'With message: 'Call to undefined method App\Models\Tasks::getRrecordById()'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(668): App\Controllers\Task->add_new_record(Object(App\Models\Tasks), '7216197231', 'chef_meijer')
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(940): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processbAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processb', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processb')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line974
[19-Jul-2018 10:19:14 Pacific/Pago_Pago] Uncaught Exception: 'Error'With message: 'Call to undefined method App\Models\Tasks::getRrecordById()'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(668): App\Controllers\Task->add_new_record(Object(App\Models\Tasks), '7216197231', 'chef_meijer')
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(952): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processdAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processd', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processd')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line974
[19-Jul-2018 10:22:07 Pacific/Pago_Pago] Uncaught Exception: 'ErrorException'With message: 'Division by zero'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(496): Core\Error::errorHandler(2, 'Division by zer...', '/home1/private/...', 496, Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(946): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processcAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processc', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processc')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line496
[19-Jul-2018 10:40:04 Pacific/Pago_Pago] Uncaught Exception: 'InstagramAPI\Exception\ChallengeRequiredException'With message: 'InstagramAPI\Response\LoginResponse: Challenge required.'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Client.php(555): InstagramAPI\Exception\ServerMessageThrower::autoThrow('InstagramAPI\\Re...', 'challenge_requi...', Object(InstagramAPI\Response\LoginResponse), Object(GuzzleHttp\Psr7\Response))
#1 /home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Request.php(793): InstagramAPI\Client->mapServerResponse(Object(InstagramAPI\Response\LoginResponse), '{"message": "ch...', Object(GuzzleHttp\Psr7\Response))
#2 /home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php(496): InstagramAPI\Request->getResponse(Object(InstagramAPI\Response\LoginResponse))
#3 /home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php(444): InstagramAPI\Instagram->_login('meowsme', 'k3kC1yxA', false, 1800)
#4 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(607): InstagramAPI\Instagram->login('meowsme', 'k3kC1yxA')
#5 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(934): App\Controllers\Task->processfunction()
#6 [internal function]: App\Controllers\Task->processaAction()
#7 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#8 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processa', Array)
#9 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processa')
#10 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Exception/ServerMessageThrower.php' on line189
[19-Jul-2018 10:44:07 Pacific/Pago_Pago] Uncaught Exception: 'ErrorException'With message: 'Division by zero'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(709): Core\Error::errorHandler(2, 'Division by zer...', '/home1/private/...', 709, Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(946): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processcAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processc', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processc')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line709
[19-Jul-2018 10:48:04 Pacific/Pago_Pago] Uncaught Exception: 'ErrorException'With message: 'Division by zero'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(496): Core\Error::errorHandler(2, 'Division by zer...', '/home1/private/...', 496, Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(940): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processbAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processb', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processb')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line496
[19-Jul-2018 10:57:19 Pacific/Pago_Pago] Uncaught Exception: 'LazyJsonMapper\Exception\LazyJsonMapperException'With message: 'Unknown function "getCode".'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(1317): LazyJsonMapper\LazyJsonMapper->__call('getCode', Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(822): App\Controllers\Task->loop_through_medias(Object(InstagramAPI\Instagram), 'usernames', Object(App\Models\Tasks), Array, Array, 200, Array)
#2 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(952): App\Controllers\Task->processfunction()
#3 [internal function]: App\Controllers\Task->processdAction()
#4 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#5 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processd', Array)
#6 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processd')
#7 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/lazyjsonmapper/lazyjsonmapper/src/LazyJsonMapper.php' on line2156
[19-Jul-2018 11:00:02 Pacific/Pago_Pago] Uncaught Exception: 'InvalidArgumentException'With message: 'You must provide a username and password to login().'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(1145): InstagramAPI\Instagram->login(NULL, NULL)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(741): App\Controllers\Task->likeMedia(Object(App\Models\Tasks), '180804303243702...', false)
#2 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(934): App\Controllers\Task->processfunction()
#3 [internal function]: App\Controllers\Task->processaAction()
#4 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#5 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processa', Array)
#6 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processa')
#7 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php' on line441
[19-Jul-2018 11:00:05 Pacific/Pago_Pago] Uncaught Exception: 'InvalidArgumentException'With message: 'You must provide a username and password to login().'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(1145): InstagramAPI\Instagram->login(NULL, NULL)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(794): App\Controllers\Task->likeMedia(Object(App\Models\Tasks), '180800029350368...', false)
#2 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(940): App\Controllers\Task->processfunction()
#3 [internal function]: App\Controllers\Task->processbAction()
#4 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#5 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processb', Array)
#6 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processb')
#7 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php' on line441
[19-Jul-2018 11:00:08 Pacific/Pago_Pago] Uncaught Exception: 'InvalidArgumentException'With message: 'You must provide a username and password to login().'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(458): InstagramAPI\Instagram->login(NULL, NULL)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(946): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processcAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processc', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processc')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php' on line441
[19-Jul-2018 11:00:11 Pacific/Pago_Pago] Uncaught Exception: 'InvalidArgumentException'With message: 'You must provide a username and password to login().'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(458): InstagramAPI\Instagram->login(NULL, NULL)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(952): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processdAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processd', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processd')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php' on line441
[19-Jul-2018 11:00:19 Pacific/Pago_Pago] Uncaught Exception: 'LazyJsonMapper\Exception\LazyJsonMapperException'With message: 'Unknown function "getCode".'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(1317): LazyJsonMapper\LazyJsonMapper->__call('getCode', Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(822): App\Controllers\Task->loop_through_medias(Object(InstagramAPI\Instagram), 'usernames', Object(App\Models\Tasks), Array, Array, 500, Array)
#2 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(962): App\Controllers\Task->processfunction()
#3 [internal function]: App\Controllers\Task->processfAction()
#4 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#5 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processf', Array)
#6 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processf')
#7 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/lazyjsonmapper/lazyjsonmapper/src/LazyJsonMapper.php' on line2156
[19-Jul-2018 11:00:20 Pacific/Pago_Pago] Uncaught Exception: 'LazyJsonMapper\Exception\LazyJsonMapperException'With message: 'Unknown function "getCode".'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(1317): LazyJsonMapper\LazyJsonMapper->__call('getCode', Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(822): App\Controllers\Task->loop_through_medias(Object(InstagramAPI\Instagram), 'usernames', Object(App\Models\Tasks), Array, Array, 550, Array)
#2 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(957): App\Controllers\Task->processfunction()
#3 [internal function]: App\Controllers\Task->processeAction()
#4 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#5 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processe', Array)
#6 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processe')
#7 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/lazyjsonmapper/lazyjsonmapper/src/LazyJsonMapper.php' on line2156
[19-Jul-2018 11:23:14 Pacific/Pago_Pago] Uncaught Exception: 'ErrorException'With message: 'Division by zero'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(814): Core\Error::errorHandler(2, 'Division by zer...', '/home1/private/...', 814, Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(957): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processeAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processe', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processe')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line814
[19-Jul-2018 11:32:13 Pacific/Pago_Pago] Uncaught Exception: 'Error'With message: 'Call to undefined method App\Models\Tasks::getRrecordById()'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(668): App\Controllers\Task->add_new_record(Object(App\Models\Tasks), '7216197231', 'chef_meijer')
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(940): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processbAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processb', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processb')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line974
[19-Jul-2018 11:36:41 Pacific/Pago_Pago] Uncaught Exception: 'Exception'With message: 'No route matched !'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('robots.txt')
#1 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/Core/Router.php' on line111
[19-Jul-2018 11:38:13 Pacific/Pago_Pago] Uncaught Exception: 'Error'With message: 'Call to undefined method App\Models\Tasks::getRrecordById()'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(668): App\Controllers\Task->add_new_record(Object(App\Models\Tasks), '7216197231', 'chef_meijer')
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(952): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processdAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processd', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processd')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line974
[19-Jul-2018 11:44:07 Pacific/Pago_Pago] Uncaught Exception: 'ErrorException'With message: 'Division by zero'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(496): Core\Error::errorHandler(2, 'Division by zer...', '/home1/private/...', 496, Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(946): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processcAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processc', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processc')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line496
[19-Jul-2018 12:00:05 Pacific/Pago_Pago] Uncaught Exception: 'ErrorException'With message: 'Division by zero'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(709): Core\Error::errorHandler(2, 'Division by zer...', '/home1/private/...', 709, Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(940): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processbAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processb', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processb')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line709
[19-Jul-2018 12:00:05 Pacific/Pago_Pago] Uncaught Exception: 'InstagramAPI\Exception\ChallengeRequiredException'With message: 'InstagramAPI\Response\LoginResponse: Challenge required.'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Client.php(555): InstagramAPI\Exception\ServerMessageThrower::autoThrow('InstagramAPI\\Re...', 'challenge_requi...', Object(InstagramAPI\Response\LoginResponse), Object(GuzzleHttp\Psr7\Response))
#1 /home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Request.php(793): InstagramAPI\Client->mapServerResponse(Object(InstagramAPI\Response\LoginResponse), '{"message": "ch...', Object(GuzzleHttp\Psr7\Response))
#2 /home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php(496): InstagramAPI\Request->getResponse(Object(InstagramAPI\Response\LoginResponse))
#3 /home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php(444): InstagramAPI\Instagram->_login('meowsme', 'k3kC1yxA', false, 1800)
#4 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(607): InstagramAPI\Instagram->login('meowsme', 'k3kC1yxA')
#5 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(934): App\Controllers\Task->processfunction()
#6 [internal function]: App\Controllers\Task->processaAction()
#7 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#8 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processa', Array)
#9 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processa')
#10 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Exception/ServerMessageThrower.php' on line189
[19-Jul-2018 12:00:14 Pacific/Pago_Pago] Uncaught Exception: 'ErrorException'With message: 'Division by zero'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(496): Core\Error::errorHandler(2, 'Division by zer...', '/home1/private/...', 496, Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(957): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processeAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processe', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processe')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line496
[19-Jul-2018 12:00:20 Pacific/Pago_Pago] Uncaught Exception: 'LazyJsonMapper\Exception\LazyJsonMapperException'With message: 'Unknown function "getCode".'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(1317): LazyJsonMapper\LazyJsonMapper->__call('getCode', Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(822): App\Controllers\Task->loop_through_medias(Object(InstagramAPI\Instagram), 'usernames', Object(App\Models\Tasks), Array, Array, 200, Array)
#2 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(962): App\Controllers\Task->processfunction()
#3 [internal function]: App\Controllers\Task->processfAction()
#4 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#5 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processf', Array)
#6 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processf')
#7 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/lazyjsonmapper/lazyjsonmapper/src/LazyJsonMapper.php' on line2156
[19-Jul-2018 12:16:06 Pacific/Pago_Pago] Uncaught Exception: 'InvalidArgumentException'With message: 'You must provide a username and password to login().'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(1145): InstagramAPI\Instagram->login(NULL, NULL)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(741): App\Controllers\Task->likeMedia(Object(App\Models\Tasks), '180804303243702...', false)
#2 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(940): App\Controllers\Task->processfunction()
#3 [internal function]: App\Controllers\Task->processbAction()
#4 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#5 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processb', Array)
#6 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processb')
#7 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php' on line441
[19-Jul-2018 12:19:10 Pacific/Pago_Pago] Uncaught Exception: 'InvalidArgumentException'With message: 'You must provide a username and password to login().'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(1145): InstagramAPI\Instagram->login(NULL, NULL)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(794): App\Controllers\Task->likeMedia(Object(App\Models\Tasks), '180800029350368...', false)
#2 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(952): App\Controllers\Task->processfunction()
#3 [internal function]: App\Controllers\Task->processdAction()
#4 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#5 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processd', Array)
#6 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processd')
#7 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php' on line441
[19-Jul-2018 12:20:01 Pacific/Pago_Pago] Uncaught Exception: 'InvalidArgumentException'With message: 'You must provide a username and password to login().'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(458): InstagramAPI\Instagram->login(NULL, NULL)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(934): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processaAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processa', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processa')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php' on line441
[19-Jul-2018 12:22:08 Pacific/Pago_Pago] Uncaught Exception: 'InvalidArgumentException'With message: 'You must provide a username and password to login().'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(458): InstagramAPI\Instagram->login(NULL, NULL)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(946): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processcAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processc', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processc')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php' on line441
[19-Jul-2018 12:23:18 Pacific/Pago_Pago] Uncaught Exception: 'LazyJsonMapper\Exception\LazyJsonMapperException'With message: 'Unknown function "getCode".'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(1317): LazyJsonMapper\LazyJsonMapper->__call('getCode', Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(822): App\Controllers\Task->loop_through_medias(Object(InstagramAPI\Instagram), 'usernames', Object(App\Models\Tasks), Array, Array, 500, Array)
#2 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(962): App\Controllers\Task->processfunction()
#3 [internal function]: App\Controllers\Task->processfAction()
#4 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#5 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processf', Array)
#6 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processf')
#7 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/lazyjsonmapper/lazyjsonmapper/src/LazyJsonMapper.php' on line2156
[19-Jul-2018 12:23:19 Pacific/Pago_Pago] Uncaught Exception: 'LazyJsonMapper\Exception\LazyJsonMapperException'With message: 'Unknown function "getCode".'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(1317): LazyJsonMapper\LazyJsonMapper->__call('getCode', Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(822): App\Controllers\Task->loop_through_medias(Object(InstagramAPI\Instagram), 'usernames', Object(App\Models\Tasks), Array, Array, 550, Array)
#2 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(957): App\Controllers\Task->processfunction()
#3 [internal function]: App\Controllers\Task->processeAction()
#4 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#5 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processe', Array)
#6 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processe')
#7 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/lazyjsonmapper/lazyjsonmapper/src/LazyJsonMapper.php' on line2156
[19-Jul-2018 12:46:13 Pacific/Pago_Pago] Uncaught Exception: 'ErrorException'With message: 'Division by zero'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(814): Core\Error::errorHandler(2, 'Division by zer...', '/home1/private/...', 814, Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(957): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processeAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processe', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processe')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line814
[19-Jul-2018 12:48:12 Pacific/Pago_Pago] Uncaught Exception: 'Error'With message: 'Call to undefined method App\Models\Tasks::getRrecordById()'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(668): App\Controllers\Task->add_new_record(Object(App\Models\Tasks), '7216197231', 'chef_meijer')
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(940): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processbAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processb', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processb')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line974
[19-Jul-2018 12:57:14 Pacific/Pago_Pago] Uncaught Exception: 'Error'With message: 'Call to undefined method App\Models\Tasks::getRrecordById()'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(668): App\Controllers\Task->add_new_record(Object(App\Models\Tasks), '7216197231', 'chef_meijer')
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(952): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processdAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processd', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processd')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line974
[19-Jul-2018 13:00:05 Pacific/Pago_Pago] Uncaught Exception: 'ErrorException'With message: 'Division by zero'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(496): Core\Error::errorHandler(2, 'Division by zer...', '/home1/private/...', 496, Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(940): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processbAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processb', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processb')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line496
[19-Jul-2018 13:16:08 Pacific/Pago_Pago] Uncaught Exception: 'InstagramAPI\Exception\ChallengeRequiredException'With message: 'InstagramAPI\Response\LoginResponse: Challenge required.'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Client.php(555): InstagramAPI\Exception\ServerMessageThrower::autoThrow('InstagramAPI\\Re...', 'challenge_requi...', Object(InstagramAPI\Response\LoginResponse), Object(GuzzleHttp\Psr7\Response))
#1 /home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Request.php(793): InstagramAPI\Client->mapServerResponse(Object(InstagramAPI\Response\LoginResponse), '{"message": "ch...', Object(GuzzleHttp\Psr7\Response))
#2 /home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php(496): InstagramAPI\Request->getResponse(Object(InstagramAPI\Response\LoginResponse))
#3 /home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php(444): InstagramAPI\Instagram->_login('meowsme', 'k3kC1yxA', false, 1800)
#4 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(607): InstagramAPI\Instagram->login('meowsme', 'k3kC1yxA')
#5 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(940): App\Controllers\Task->processfunction()
#6 [internal function]: App\Controllers\Task->processbAction()
#7 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#8 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processb', Array)
#9 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processb')
#10 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Exception/ServerMessageThrower.php' on line189
[19-Jul-2018 13:19:10 Pacific/Pago_Pago] Uncaught Exception: 'ErrorException'With message: 'Division by zero'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(709): Core\Error::errorHandler(2, 'Division by zer...', '/home1/private/...', 709, Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(952): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processdAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processd', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processd')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line709
[19-Jul-2018 13:23:13 Pacific/Pago_Pago] Uncaught Exception: 'ErrorException'With message: 'Division by zero'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(496): Core\Error::errorHandler(2, 'Division by zer...', '/home1/private/...', 496, Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(957): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processeAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processe', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processe')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line496
[19-Jul-2018 13:23:24 Pacific/Pago_Pago] Uncaught Exception: 'LazyJsonMapper\Exception\LazyJsonMapperException'With message: 'Unknown function "getCode".'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(1317): LazyJsonMapper\LazyJsonMapper->__call('getCode', Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(822): App\Controllers\Task->loop_through_medias(Object(InstagramAPI\Instagram), 'usernames', Object(App\Models\Tasks), Array, Array, 200, Array)
#2 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(962): App\Controllers\Task->processfunction()
#3 [internal function]: App\Controllers\Task->processfAction()
#4 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#5 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processf', Array)
#6 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processf')
#7 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/lazyjsonmapper/lazyjsonmapper/src/LazyJsonMapper.php' on line2156
[19-Jul-2018 13:32:05 Pacific/Pago_Pago] Uncaught Exception: 'InvalidArgumentException'With message: 'You must provide a username and password to login().'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(1145): InstagramAPI\Instagram->login(NULL, NULL)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(741): App\Controllers\Task->likeMedia(Object(App\Models\Tasks), '180804303243702...', false)
#2 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(940): App\Controllers\Task->processfunction()
#3 [internal function]: App\Controllers\Task->processbAction()
#4 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#5 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processb', Array)
#6 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processb')
#7 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php' on line441
[19-Jul-2018 13:38:13 Pacific/Pago_Pago] Uncaught Exception: 'InvalidArgumentException'With message: 'You must provide a username and password to login().'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(1145): InstagramAPI\Instagram->login(NULL, NULL)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(794): App\Controllers\Task->likeMedia(Object(App\Models\Tasks), '180800029350368...', false)
#2 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(952): App\Controllers\Task->processfunction()
#3 [internal function]: App\Controllers\Task->processdAction()
#4 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#5 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processd', Array)
#6 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processd')
#7 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php' on line441
[19-Jul-2018 13:40:02 Pacific/Pago_Pago] Uncaught Exception: 'InvalidArgumentException'With message: 'You must provide a username and password to login().'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(458): InstagramAPI\Instagram->login(NULL, NULL)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(934): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processaAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processa', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processa')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php' on line441
[19-Jul-2018 13:44:07 Pacific/Pago_Pago] Uncaught Exception: 'InvalidArgumentException'With message: 'You must provide a username and password to login().'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(458): InstagramAPI\Instagram->login(NULL, NULL)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(946): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processcAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processc', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processc')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php' on line441
[19-Jul-2018 13:46:20 Pacific/Pago_Pago] Uncaught Exception: 'LazyJsonMapper\Exception\LazyJsonMapperException'With message: 'Unknown function "getCode".'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(1317): LazyJsonMapper\LazyJsonMapper->__call('getCode', Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(822): App\Controllers\Task->loop_through_medias(Object(InstagramAPI\Instagram), 'usernames', Object(App\Models\Tasks), Array, Array, 500, Array)
#2 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(962): App\Controllers\Task->processfunction()
#3 [internal function]: App\Controllers\Task->processfAction()
#4 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#5 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processf', Array)
#6 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processf')
#7 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/lazyjsonmapper/lazyjsonmapper/src/LazyJsonMapper.php' on line2156
[19-Jul-2018 13:46:21 Pacific/Pago_Pago] Uncaught Exception: 'LazyJsonMapper\Exception\LazyJsonMapperException'With message: 'Unknown function "getCode".'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(1317): LazyJsonMapper\LazyJsonMapper->__call('getCode', Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(822): App\Controllers\Task->loop_through_medias(Object(InstagramAPI\Instagram), 'usernames', Object(App\Models\Tasks), Array, Array, 550, Array)
#2 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(957): App\Controllers\Task->processfunction()
#3 [internal function]: App\Controllers\Task->processeAction()
#4 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#5 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processe', Array)
#6 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processe')
#7 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/lazyjsonmapper/lazyjsonmapper/src/LazyJsonMapper.php' on line2156
[19-Jul-2018 14:00:08 Pacific/Pago_Pago] Uncaught Exception: 'ErrorException'With message: 'Division by zero'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(814): Core\Error::errorHandler(2, 'Division by zer...', '/home1/private/...', 814, Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(946): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processcAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processc', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processc')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line814
[19-Jul-2018 14:00:24 Pacific/Pago_Pago] Uncaught Exception: 'Error'With message: 'Call to undefined method App\Models\Tasks::getRrecordById()'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(668): App\Controllers\Task->add_new_record(Object(App\Models\Tasks), '7216197231', 'chef_meijer')
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(957): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processeAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processe', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processe')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line974
[19-Jul-2018 14:00:24 Pacific/Pago_Pago] Uncaught Exception: 'Error'With message: 'Call to undefined method App\Models\Tasks::getRrecordById()'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(668): App\Controllers\Task->add_new_record(Object(App\Models\Tasks), '7216197231', 'chef_meijer')
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(962): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processfAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processf', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processf')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line974
[19-Jul-2018 14:19:11 Pacific/Pago_Pago] Uncaught Exception: 'ErrorException'With message: 'Division by zero'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(496): Core\Error::errorHandler(2, 'Division by zer...', '/home1/private/...', 496, Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(952): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processdAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processd', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processd')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line496
[19-Jul-2018 14:32:07 Pacific/Pago_Pago] Uncaught Exception: 'InstagramAPI\Exception\ChallengeRequiredException'With message: 'InstagramAPI\Response\LoginResponse: Challenge required.'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Client.php(555): InstagramAPI\Exception\ServerMessageThrower::autoThrow('InstagramAPI\\Re...', 'challenge_requi...', Object(InstagramAPI\Response\LoginResponse), Object(GuzzleHttp\Psr7\Response))
#1 /home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Request.php(793): InstagramAPI\Client->mapServerResponse(Object(InstagramAPI\Response\LoginResponse), '{"message": "ch...', Object(GuzzleHttp\Psr7\Response))
#2 /home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php(496): InstagramAPI\Request->getResponse(Object(InstagramAPI\Response\LoginResponse))
#3 /home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php(444): InstagramAPI\Instagram->_login('meowsme', 'k3kC1yxA', false, 1800)
#4 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(607): InstagramAPI\Instagram->login('meowsme', 'k3kC1yxA')
#5 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(940): App\Controllers\Task->processfunction()
#6 [internal function]: App\Controllers\Task->processbAction()
#7 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#8 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processb', Array)
#9 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processb')
#10 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Exception/ServerMessageThrower.php' on line189
[19-Jul-2018 14:38:10 Pacific/Pago_Pago] Uncaught Exception: 'ErrorException'With message: 'Division by zero'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(709): Core\Error::errorHandler(2, 'Division by zer...', '/home1/private/...', 709, Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(952): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processdAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processd', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processd')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line709
[19-Jul-2018 14:46:13 Pacific/Pago_Pago] Uncaught Exception: 'ErrorException'With message: 'Division by zero'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(496): Core\Error::errorHandler(2, 'Division by zer...', '/home1/private/...', 496, Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(957): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processeAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processe', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processe')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line496
[19-Jul-2018 14:46:25 Pacific/Pago_Pago] Uncaught Exception: 'LazyJsonMapper\Exception\LazyJsonMapperException'With message: 'Unknown function "getCode".'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(1317): LazyJsonMapper\LazyJsonMapper->__call('getCode', Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(822): App\Controllers\Task->loop_through_medias(Object(InstagramAPI\Instagram), 'usernames', Object(App\Models\Tasks), Array, Array, 200, Array)
#2 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(962): App\Controllers\Task->processfunction()
#3 [internal function]: App\Controllers\Task->processfAction()
#4 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#5 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processf', Array)
#6 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processf')
#7 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/lazyjsonmapper/lazyjsonmapper/src/LazyJsonMapper.php' on line2156
[19-Jul-2018 14:48:05 Pacific/Pago_Pago] Uncaught Exception: 'InvalidArgumentException'With message: 'You must provide a username and password to login().'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(1145): InstagramAPI\Instagram->login(NULL, NULL)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(741): App\Controllers\Task->likeMedia(Object(App\Models\Tasks), '180804303243702...', false)
#2 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(940): App\Controllers\Task->processfunction()
#3 [internal function]: App\Controllers\Task->processbAction()
#4 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#5 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processb', Array)
#6 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processb')
#7 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php' on line441
[19-Jul-2018 14:57:10 Pacific/Pago_Pago] Uncaught Exception: 'InvalidArgumentException'With message: 'You must provide a username and password to login().'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(1145): InstagramAPI\Instagram->login(NULL, NULL)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(794): App\Controllers\Task->likeMedia(Object(App\Models\Tasks), '180800029350368...', false)
#2 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(952): App\Controllers\Task->processfunction()
#3 [internal function]: App\Controllers\Task->processdAction()
#4 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#5 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processd', Array)
#6 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processd')
#7 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php' on line441
[19-Jul-2018 15:00:02 Pacific/Pago_Pago] Uncaught Exception: 'InvalidArgumentException'With message: 'You must provide a username and password to login().'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(458): InstagramAPI\Instagram->login(NULL, NULL)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(934): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processaAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processa', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processa')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php' on line441
[19-Jul-2018 15:00:05 Pacific/Pago_Pago] Uncaught Exception: 'InvalidArgumentException'With message: 'You must provide a username and password to login().'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(458): InstagramAPI\Instagram->login(NULL, NULL)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(940): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processbAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processb', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processb')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/mgp25/instagram-php/src/Instagram.php' on line441
[19-Jul-2018 15:00:13 Pacific/Pago_Pago] Uncaught Exception: 'LazyJsonMapper\Exception\LazyJsonMapperException'With message: 'Unknown function "getCode".'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(1317): LazyJsonMapper\LazyJsonMapper->__call('getCode', Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(822): App\Controllers\Task->loop_through_medias(Object(InstagramAPI\Instagram), 'usernames', Object(App\Models\Tasks), Array, Array, 500, Array)
#2 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(952): App\Controllers\Task->processfunction()
#3 [internal function]: App\Controllers\Task->processdAction()
#4 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#5 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processd', Array)
#6 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processd')
#7 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/lazyjsonmapper/lazyjsonmapper/src/LazyJsonMapper.php' on line2156
[19-Jul-2018 15:00:17 Pacific/Pago_Pago] Uncaught Exception: 'LazyJsonMapper\Exception\LazyJsonMapperException'With message: 'Unknown function "getCode".'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(1317): LazyJsonMapper\LazyJsonMapper->__call('getCode', Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(822): App\Controllers\Task->loop_through_medias(Object(InstagramAPI\Instagram), 'usernames', Object(App\Models\Tasks), Array, Array, 550, Array)
#2 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(946): App\Controllers\Task->processfunction()
#3 [internal function]: App\Controllers\Task->processcAction()
#4 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#5 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processc', Array)
#6 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processc')
#7 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/vendor/lazyjsonmapper/lazyjsonmapper/src/LazyJsonMapper.php' on line2156
[19-Jul-2018 15:20:01 Pacific/Pago_Pago] Uncaught Exception: 'ErrorException'With message: 'Division by zero'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(814): Core\Error::errorHandler(2, 'Division by zer...', '/home1/private/...', 814, Array)
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(934): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processaAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processa', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processa')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line814
[19-Jul-2018 15:23:21 Pacific/Pago_Pago] Uncaught Exception: 'Error'With message: 'Call to undefined method App\Models\Tasks::getRrecordById()'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(668): App\Controllers\Task->add_new_record(Object(App\Models\Tasks), '7216197231', 'chef_meijer')
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(957): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processeAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processe', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processe')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line974
[19-Jul-2018 15:23:22 Pacific/Pago_Pago] Uncaught Exception: 'Error'With message: 'Call to undefined method App\Models\Tasks::getRrecordById()'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(668): App\Controllers\Task->add_new_record(Object(App\Models\Tasks), '7216197231', 'chef_meijer')
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(962): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processfAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processf', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processf')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line974
[19-Jul-2018 15:34:18 Pacific/Pago_Pago] Uncaught Exception: 'Exception'With message: 'No route matched !'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('')
#1 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/Core/Router.php' on line111
[19-Jul-2018 15:42:04 Pacific/Pago_Pago] Uncaught Exception: 'Error'With message: 'Call to undefined method App\Models\Tasks::getRrecordById()'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(429): App\Controllers\Task->add_new_record(Object(App\Models\Tasks), '8011464796', 'adventuretravel...')
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(934): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processaAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processa', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processa')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line974
[19-Jul-2018 15:42:07 Pacific/Pago_Pago] Uncaught Exception: 'Error'With message: 'Call to undefined method App\Models\Tasks::getRrecordById()'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(1240): App\Controllers\Task->add_new_record(Object(App\Models\Tasks), '7462340450', 'davelarry_crypt...')
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(504): App\Controllers\Task->loop_through_pks(Object(InstagramAPI\Instagram), 'hashtags', Object(App\Models\Tasks), Array, Array, 10, Array)
#2 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(940): App\Controllers\Task->processfunction()
#3 [internal function]: App\Controllers\Task->processbAction()
#4 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#5 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processb', Array)
#6 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processb')
#7 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line974
[19-Jul-2018 15:42:13 Pacific/Pago_Pago] Uncaught Exception: 'Error'With message: 'Call to undefined method App\Models\Tasks::getRrecordById()'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(1355): App\Controllers\Task->add_new_record(Object(App\Models\Tasks), '182732819463979...', 'Blb-U-5j5Pw')
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(717): App\Controllers\Task->loop_through_medias(Object(InstagramAPI\Instagram), 'hashtags', Object(App\Models\Tasks), Array, Array, 20, Array)
#2 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(934): App\Controllers\Task->processfunction()
#3 [internal function]: App\Controllers\Task->processaAction()
#4 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#5 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processa', Array)
#6 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processa')
#7 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line974
[19-Jul-2018 15:43:06 Pacific/Pago_Pago] Uncaught Exception: 'Error'With message: 'Call to undefined method App\Models\Tasks::getRrecordById()'
Stack Trace: '#0 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(429): App\Controllers\Task->add_new_record(Object(App\Models\Tasks), '8011464796', 'adventuretravel...')
#1 /home1/private/public_html/instapp/fct1/App/Controllers/Task.php(940): App\Controllers\Task->processfunction()
#2 [internal function]: App\Controllers\Task->processbAction()
#3 /home1/private/public_html/instapp/fct1/Core/Controller.php(53): call_user_func_array(Array, Array)
#4 /home1/private/public_html/instapp/fct1/Core/Router.php(100): Core\Controller->__call('processb', Array)
#5 /home1/private/public_html/instapp/fct1/public/index.php(46): Core\Router->dispatch('task/processb')
#6 {main}
Thrown in: '/home1/private/public_html/instapp/fct1/App/Controllers/Task.php' on line974
